### ISSUE TITLE
Migrate to Kotlin

### ISSUE THREAD

**Issue by raghavtilak** [raghavtilak/GFGTextSticker#1]

**Comment by SaranshBaniyal** [comment]
Hello @raghavtilak I have had past experience in kotlin and java based native android dev, would love to contribute. Please assign this issue to me

**Comment by raghavtilak** [comment]
Hey @SaranshBaniyal 
Sure, I'd be happy to assign you this issue.
If you have any questions or need further information about the issue, please feel free to reach out. I'm here to help.
Go for it 👍🏻

**Comment by SaranshBaniyal** [comment]
Thanks @raghavtilak

**Comment by raghavtilak** [comment]
Thanks for your contribution @SaranshBaniyal  😄👍🏻
